name: pixel_prompt
description: A terminal UI (TUI) framework for Dart.
version: 0.0.1

environment:
  sdk: ^3.8.1

homepage: https://github.com/primequantuM4/pixel_prompt
repository: https://github.com/primequantuM4/pixel_prompt
issue_tracker: https://github.com/primequantuM4/pixel_prompt/issues

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
